---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-deployment
  labels:
    type: result-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: result-app
  template:
    metadata:
      name: resultapp-pod
      labels:
        type: result-app
    spec:
      containers:
        - name: myresult-app
          image: dockersamples/examplevotingapp_result
...