---
apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    type: result-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: result-app
...