---
apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    type: votingapp
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: votingapp
...